# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f011dd479ff1ecb49173ee1e2a405144d953590793aca3d4494c081b05a022210eae9855dcc9cc0654a267dab3d01843023fe62d4d7ce8699e0b0242e7ee70bf

test:
  secret_key_base: bfa78918c6dd74e49c4bcc421afbad2577ec2f7d9ad1006bc265eafdbe9844dcfc45b82beca8cdeba0a69641553be3bdf7da1520c48e1bcab99d28698fbc3212

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
